# SwiftLint Configuration for ghostty-layout
# Based on oss-docs-templates with project-specific adjustments

# Paths to include in linting
included:
  - Sources
  - Tests

# Paths to exclude from linting
excluded:
  - .build
  - DerivedData
  - .swiftpm

# Reporter format
reporter: xcode

# Rule Configuration
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - sorted_first_last

disabled_rules:
  - todo  # Allow TODO comments in development

# Line length
line_length:
  warning: 150  # Adjusted for Japanese error messages
  error: 300    # Adjusted for long test strings
  ignores_comments: true
  ignores_urls: true

# File length
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

# Function length
function_body_length:
  warning: 50
  error: 100

# Type body length
type_body_length:
  warning: 300
  error: 500

# Identifier name lengths
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - to
    - db
    - x
    - y

# Nesting depth
nesting:
  type_level:
    warning: 2

# Custom rules can be added below
# custom_rules:
