name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below to help us fix it.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: |
        When I run `ghostty-layout 2x3`, the panes are not split correctly...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Open Ghostty terminal
        2. Run `ghostty-layout 2x3`
        3. Observe that the layout is incorrect
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen
      placeholder: A 2x3 grid layout should be applied to the Ghostty terminal
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened (include error messages if any)
      placeholder: |
        Error: Accessibility permissions required...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: ghostty-layout version
      description: Run `ghostty-layout --version`
      placeholder: "0.3.0"
    validations:
      required: true

  - type: input
    id: swift
    attributes:
      label: Swift version
      description: Run `swift --version`
      placeholder: "swift-driver version: 1.87.1 Apple Swift version 5.9.2"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: macOS version
      description: e.g., macOS 14.2, macOS 15.0
      placeholder: "macOS 14.2"
    validations:
      required: true

  - type: input
    id: ghostty
    attributes:
      label: Ghostty version
      description: The version of Ghostty terminal you are using
      placeholder: "1.0.0"
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Ghostty config (relevant keybindings)
      description: Paste relevant keybind lines from your Ghostty config file
      placeholder: |
        keybind = cmd+d=new_split:right
        keybind = cmd+shift+d=new_split:down
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, screenshots, or logs that might help
    validations:
      required: false
